# Generated by Django 5.1.6 on 2025-02-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salattimetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
