# Generated by Django 5.1.6 on 2025-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salattimetable', '0002_useraccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
